# dataframe

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('Employers_data.csv')

In [5]:
df.head()

Employee_ID            Name  Age  Gender   Department  Job_Title  \
0            1    Merle Ingram   24  Female  Engineering   Engineer   
1            2      John Mayes   56    Male        Sales  Executive   
2            3    Carlos Wille   21    Male  Engineering     Intern   
3            4  Michael Bryant   30    Male      Finance    Analyst   
4            5   Paula Douglas   25  Female           HR    Analyst   

   Experience_Years Education_Level  Location  Salary  
0                 1          Master    Austin   90000  
1                33          Master   Seattle  195000  
2                 1        Bachelor  New York   35000  
3                 9        Bachelor  New York   75000  
4                 2          Master   Seattle   70000

In [6]:
df.describe()

Employee_ID           Age  Experience_Years         Salary
count  10000.00000  10000.000000      10000.000000   10000.000000
mean    5000.50000     35.455900         12.370900  115381.500000
std     2886.89568     10.000213          9.148951   46066.139047
min        1.00000     21.000000          0.000000   25000.000000
25%     2500.75000     27.000000          5.000000   70000.000000
50%     5000.50000     34.000000         10.000000  120000.000000
75%     7500.25000     43.000000         19.000000  150000.000000
max    10000.00000     60.000000         37.000000  215000.000000

In [9]:
n=5
while n>0:
    print(n)
    n=n-1
print(n)

5
4
3
2
1
0


In [10]:
while True:
    line=input(' ')
    if line=='done':
        break
    print(line)
print('done!')

  gh


gh


  done


done!


In [11]:
while True:
    line=input(' ')
    if line[0]=='a':
        continue
    if line == 'done':
        break
    print(line)
print('Done!')

  a
  done


Done!


In [13]:
friends=['John', 'Tom', 'Tim']
for i in friends:
    print('I love you:', i)
print('Done')

I love you: John
I love you: Tom
I love you: Tim
Done


In [17]:
largest= -1
for i in [2, 43, 45, 12 ,3, 9]:
    if i>largest:
        largest=i
print('largest: ', largest)

largest:  45


In [19]:
sum=0
for i in [1,2,3,4,5]:
    sum=sum+i
print(sum)
avg=sum/5
print(avg)

15
3.0


In [3]:
apple=input('Enter:')
x = int(apple)  - 20
print(x)

Enter: 100


80


In [7]:
abc='mango'
print(abc[4])

o


In [1]:
name='Lorish'
print(len(name))

6


In [2]:
fruit='apple'
index=0
while index<len(fruit):
    letter=fruit[index]
    print(index, letter)
    index=index+1

0 a
1 p
2 p
3 l
4 e


In [4]:
fruit='apple'
for index in fruit:
    print(index)


a
p
p
l
e


In [5]:
fruit='banana'
count=0
for letter in fruit:
    if letter =='a':
        count = count+1
print(count)

3


In [8]:
s='monty python'
print(s[6:])

python


In [10]:
name='Lorish'
'r' in name
if 'h' in name:
    print('Found')

Found


In [12]:
stuff='hello world'
type(stuff)
dir(stuff)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

# array python

In [6]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
arr=np.array([1,2,3], ndmin=5)
print(arr)
print('number of dimensions: ',arr.ndim)

[[[[[1 2 3]]]]]
number of dimensions:  5


In [12]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr[0,1])

2nd element on 1st row:  2


In [13]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [14]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [17]:
arr=np.array([1,2,3,4,4,5])
x=np.where(arr==9)
print(x)

(array([], dtype=int64),)


In [19]:
arr=np.array([1,2,3,6,4])
print(np.sort(arr))

[1 2 3 4 6]


In [21]:
arr=np.array([21,22,23,24])
x=[True, False, True, False]
newarr=arr[x]
print(newarr)

[21 23]


# counting and spliting

In [22]:
#counting and slipting
count=dict()
print("enter line of words:")
line=input('')
words=line.replace(","," ").split()
print(words)

print("counting")
for word in words:
    count[word]=count.get(word,0)+1
print(count)

enter line of words:


 hello this is a test test


['hello', 'this', 'is', 'a', 'test', 'test']
counting
{'hello': 1, 'this': 1, 'is': 1, 'a': 1, 'test': 2}


In [26]:
count=dict()
print("enter a line of words: ")
line=input('')
words=line.split()
print(words)

print("counting")
for word in words:
    count[word]=count.get(word,0)+1
print(count)

concat=''
add=0
for word in words:
    try:
        re=int(word)
        add=add+int(word)
        concat += word
    except:
        pass
print('concatenation: ',concat)
print('add: ',add)

special_char=['!','#','$','%','&','*']
special_stat=False

for word in words:
    if word in special_char:
        special_stat=True
        break
if special_stat:
    print('special char found')
else:
    print('special char not found')
    

enter a line of words: 


 hello ! my name is chad


['hello', '!', 'my', 'name', 'is', 'chad']
counting
{'hello': 1, '!': 1, 'my': 1, 'name': 1, 'is': 1, 'chad': 1}
concatenation:  
add:  0
special char found


# function

In [2]:
def hello(): #no parameters
    print("Hello world")
hello()

Hello world


In [3]:
def add(a,b):
    return a+b
result=add(5,4)
print(result)

9


In [6]:
def greet(name="John"): #function with default parameter
    print("Hello, "+ name + "!")
greet()
greet("Tom")

Hello, John!
Hello, Tom!


In [8]:
#function to check even or odd
def is_even(num):
    if num%2== 0:
        return True
    else:
        return False
print(is_even(8))

True


In [1]:
#max fnc
def find_max(a,b,c,d):
    return max(a,b,c,d)
print(find_max(2,3,5,6))

6


In [5]:
#number game
import random
def guess_num():
    number=random.randint(1,10)
    guess=int(input("guess a number between 1 to 10: "))

    if guess==number:
        print("you guessed it!")
    else:
        print(f"the number was {number} ")
guess_num()

guess a number between 1 to 10:  2


the number was 10 


In [6]:
import random
def roll_dice():
    return random.randint(1,6)
while True:
    input("Press enter to roll the dice...")
    print("you rolled: ", roll_dice())
    again=input("roll again?(y/n): ")
    if again.lower() !='y':
        break

Press enter to roll the dice... 


you rolled:  4


roll again?(y/n):  y
Press enter to roll the dice... 


you rolled:  2


roll again?(y/n):  n


# Dice Roll

In [9]:
import tkinter as tk
import random

def roll_dice():
    dice_value = random.randint(1,6)
    label_result.config(text = f"You rolled: {dice_value}")
    dice_label.config(text=dice_unicode[dice_value])           

#unicode characters for dice faces 1-6
dice_unicode = {
    1: "\u2680",
    2: "\u2681",
    3: "\u2682",
    4: "\u2683",
    5: "\u2684",
    6: "\u2685"
}

#create main window
root = tk.Tk()
root.title("Dice Rolla")
root.geometry("300x300")

#dice face display
dice_label = tk.Label(root, text = "DICE ROLLER", font = ("Helvetica", 20))
dice_label.pack()

#result text display
label_result = tk.Label(root, text = "Click to roll the dice!", font = ("Helvetica", 14))
label_result.pack(pady=10)

#roll button
roll_button = tk.Button(root, text = "Roll the dice!", command = roll_dice, font = ("Helvetica", 12))
roll_button.pack()

#run the gui loop
root.mainloop()